name: wintrchess

services:
  app:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - .env
    depends_on:
      - database
  database:
    image: mongo:latest
    volumes:
      - wintrchess-database:/data/db
    attach: false

volumes:
  wintrchess-database: